### ISSUE TITLE
Village number

### ISSUE THREAD

**Issue by LBIRE** [ACROSS-Lab/BacHungHai-Waste#11]
Make appear village number in a way that the players can locate their village

**Comment by ptaillandier** [comment]
I just added a new model to present the game. For the main "game", should we add the village number somewhere?

**Comment by LBIRE** [comment]
Thank you for the presentation model. For the game model, i think it would be good to add each village number close to it, we have margins where we can put text (with arrows or lines for example ?)

**Comment by ptaillandier** [comment]
done, you can test it

**Comment by LBIRE** [comment]
Presentation model works, and village name appear in the debug game model
