### ISSUE TITLE
Find a name for the game

### ISSUE THREAD

**Issue by ptaillandier** [ACROSS-Lab/BacHungHai-Waste#14]
For example, EcoGame ?

**Comment by LBIRE** [comment]
Nga proposed :
Wat-a-waste
Wat-a-crop

But we don't know if it's considered as intellectual theft

**Comment by AlexisDrogoul** [comment]
And something that would sound a bit more Vietnamese ? Or we ask the students at the French school to participate to a contest to find the best name ?

**Comment by LBIRE** [comment]
Name defined as "RÁC"
