### ISSUE TITLE
Parameter action pesticides

### ISSUE THREAD

**Issue by LBIRE** [ACROSS-Lab/BacHungHai-Waste#17]
We would like to change the reduction of waste from farmers with this action from solid waste to waste water but I can't find the proper code line to replace the current one acting on solid waste in the fields

**Comment by ptaillandier** [comment]
for the moment, the action reduces both the solid and water waste produced b y agriculture (see Agricultural Space -> species plot -> Action pollution_due_to_practice.

**Comment by LBIRE** [comment]
Fixed
