### ISSUE TITLE
Parameter action fallow

### ISSUE THREAD

**Issue by LBIRE** [ACROSS-Lab/BacHungHai-Waste#18]
One of the parameters for the fallow action is not working :
- The reduction of production on the first year is working well. 
- The parameter to decrease ground pollution is not effective (I tried with big numbers, both for the action itself and for the impact of pollution on production)

**Comment by ptaillandier** [comment]
I am not sure what this action is supposed to do in terms of diminution of the ground pollution:
 - impact water waste and/or solid waste 
 - decrease the pollution for all "cells" of the village or for the cells inside plots or for a certain number of cells in plots ?
 - decrease the waste by a value or by a certain coefficient

**Comment by LBIRE** [comment]
Implement the possibility to adjust a parameter in the action to improve agricultural production for one year. 
Ideally, it would be nice to have the same possibility as the action drain and dredge (variable dedicated to the action's capacity to improve agricultural production)

**Comment by LBIRE** [comment]
Issue fixed
