### ISSUE TITLE
Problem importing pollution_density variable for functions

### ISSUE THREAD

**Issue by LBIRE** [ACROSS-Lab/BacHungHai-Waste#19]
After having taken the variable pollution_density for canals pollution classes (map), the variable is not imported correctly (error)

int water_pollution_class_current(canal p) {
		float w <- pollution_density;
		switch(w) {
			match_between [0, 0.9] {return 0;}
			match_between [1, 9] {return 1;}
			match_between [10, 19] {return 2;}
			match_between [20, 39] {return 3;}
			default {return 4;}

**Comment by AlexisDrogoul** [comment]
it has to be written `p.pollution_density`(i.e., the pollution density of the canal p). I fixed it.
