### ISSUE TITLE
Timer for cagnotte

### ISSUE THREAD

**Issue by LBIRE** [ACROSS-Lab/BacHungHai-Waste#27]
Design a timer for the cagnotte. 
Players have 1 minute to decide on the extra action to take with the remaining money. If the timer is excessed and the players didn't reach an agreement, they lose the remaining money.

**Comment by AlexisDrogoul** [comment]
see https://github.com/WARMTeam/BacHungHai-Waste/commit/c576ce4696aa0649259d5f10ce9b1f5a051fb90b

**Comment by LBIRE** [comment]
Issue fixed
