### ISSUE TITLE
Delete action 1 as compulsory every turn

### ISSUE THREAD

**Issue by LBIRE** [ACROSS-Lab/BacHungHai-Waste#28]
These last few tests, we experienced a bias in the use of action 1. Since it's mandatory, players don't see the point in taking the higher level of the action. 

Therefore :
- Delete the level of the action and keep only action B. 
- Implement in the model the passage of collection teams twice a week as systematic, without making the players pay for it. 
- Re-calibrate the budget of the players considering 30 tokens won't be spent systematically for the collection team. 
- Reduce the cost of the action 1 (double the frequency of collection teams) to 40 tokens instead of 50 tokens. 
- The action stays a punctual action : if the player chose it, the collection team frequency will double only for the next round.

**Comment by ptaillandier** [comment]
I changed the model on that. Tested needed!

**Comment by LBIRE** [comment]
Issue fixed
