### ISSUE TITLE
Cagnotte interface integration

### ISSUE THREAD

**Issue by LBIRE** [ACROSS-Lab/BacHungHai-Waste#29]
Make so that the cagnotte is a whole phase which appears at the top of the interface. 
Suppress any popups and rely on buttons. 

See issue #27 to add a strict timer once it's done.

**Comment by AlexisDrogoul** [comment]
See https://github.com/WARMTeam/BacHungHai-Waste/commit/c576ce4696aa0649259d5f10ce9b1f5a051fb90b

**Comment by LBIRE** [comment]
Issue fixed
