### ISSUE TITLE
Change icon solid waste pollution

### ISSUE THREAD

**Issue by LBIRE** [ACROSS-Lab/BacHungHai-Waste#30]
The icon for the solid waste pollution is not understood correctly by the players (cloud, pile of candies, ...). Maybe we should replace it with something more symbolic like a trash bag ?

**Comment by AlexisDrogoul** [comment]
![dump-2](https://user-images.githubusercontent.com/579256/174045076-b0a69ffb-35d2-4282-b3dd-d68d3118baf4.png)
![dump](https://user-images.githubusercontent.com/579256/174045086-5af525cf-546a-4beb-b8e6-8bd991937150.png)
![garbage-2](https://user-images.githubusercontent.com/579256/174045093-af32896c-2933-4b64-9899-4d273459f0a9.png)
![garbage-3](https://user-images.githubusercontent.com/579256/174045098-5fdb6e6f-d064-430f-8b80-637f9d58655e.png)
![garbage-4](https://user-images.githubusercontent.com/579256/174045103-dd912699-ff79-4689-b18e-20922047f932.png)
![landfill](https://user-images.githubusercontent.com/579256/174045107-17fed1c1-848c-4120-827c-d56c2dee5aaa.png)
![trash](https://user-images.githubusercontent.com/579256/174045109-3e6c4621-bcac-4897-bd5a-4731746bb6ba.png)
![waste-2](https://user-images.githubusercontent.com/579256/174045115-43f273f3-dd3d-4ceb-9dbe-2df4c4da6869.png)
![waste-3](https://user-images.githubusercontent.com/579256/174045122-c811e1b4-3c94-4a86-8e33-9cb8ab3cd562.png)
![water-2](https://user-images.githubusercontent.com/579256/174045127-3652ce06-f6bb-4e64-aefa-6b7d72dd0471.png)

Any one of these ?
