### ISSUE TITLE
Reduce annual population increase

### ISSUE THREAD

**Issue by LBIRE** [ACROSS-Lab/BacHungHai-Waste#5]
Reduce by half the annual population growth. I can't find it in the parameters, the line : 
'''float min_increase_urban_area_population_year <- 0.05; //min increase of urban area per year (in terms of number of people)'''
doesn't seem to work after several modifications

**Comment by ptaillandier** [comment]
My last commit should fixed that. You have now information about the population (farmer and living in urban area) in the info panel.
