### ISSUE TITLE
Increase budget every year

### ISSUE THREAD

**Issue by LBIRE** [ACROSS-Lab/BacHungHai-Waste#6]
Increase budget every year, proportionally to population growth

**Comment by ptaillandier** [comment]
Should the initial budget be computed from the initial population? 
Do you have a formulae to propose?

**Comment by AlexisDrogoul** [comment]
And should we have a portion of it depending on the global sales of agricultural products ? So that bad performances in obtaining the label are somehow reflected in a smaller budget ?

**Comment by LBIRE** [comment]
We could begin the game round 1 with 120 tokens and assign its rate to the original number of inhabitants. Strictly about the budget, we could propose:
Budget of the current round = 120*y
y = population growth rate 

For Alexis proposal, I think it is a good idea to add some incentive in meeting the EcoLabel criteria. However due to our scenario (ecolabel being essential to farmers to sell their products), i can't think for now of a solution that is not too much prohibitive for most rounds during the game.

**Comment by ptaillandier** [comment]
It is now possible to define the formulae of the budget in Parameter (to be defined).

**Comment by LBIRE** [comment]
Evolution formulae for the budget works fine

**Comment by LBIRE** [comment]
Update formulae to base budget on an increase if the previous year production has increased for the village :
_Formulae in coming_

**Comment by LBIRE** [comment]
Fixed : budget now depends on the production level of the previous year
