### ISSUE TITLE
Pop up ecolabel

### ISSUE THREAD

**Issue by LBIRE** [ACROSS-Lab/BacHungHai-Waste#8]
Create a pop up to highlight where the commune is at regarding ecolabel. I think it should come up at the end of each computation (before deciding on actions)

**Comment by ptaillandier** [comment]
I added several "visual" features to directly see if the commune meets the ecolabel standard:
 - add the information in the info panel
 - color the info panel according to these conditions
 - add information at the beginning of player turn
 - change the color of the data series in the global indicators according to the respect of the conditions
